export interface Book{
    author?: string,
    box_office?: string,
    budget?: string,
    cinematographers?: string[],
    cover?: string,
    dedication?: string,
    directors?: string[],
    distributors?: string[],
    editors?: string[],
    music_composers?: string[],
    pages?: number,
    poster?: string,
    producers?: string[],
    rating?: string,
    release_date: string,
    running_time?: string,
    screenwriters?: string[],
    slug: string,
    summary: string,
    title: string,
    trailer?: string,
    wiki: string,
}