export interface Character{
    alias_names: Array<string>,
    animagus: string,
    blood_status: string,
    boggart: string,
    born: string,
    died: string,
    eye_color: string,
    family_members: Array<string>,
    gender: string,
    hair_color: string,
    height: string,
    house: string,
    image: string,
    jobs: Array<string>,
    marital_status: string,
    name: string,
    nationality: string,
    patronus: string,
    romances: Array<string>,
    skin_color: string,
    slug: string,
    species: string,
    titles: Array<string>,
    wands: Array<string>,
    weight: string,
    wiki: string,
}