export interface Movie{
    box_office: string,
    budget: string,
    cinematographers: Array<string>,
    directors: Array<string>,
    distributors: Array<string>,
    editors: Array<string>,
    music_composers: Array<string>,
    poster: string,
    producers: Array<string>,
    rating: string,
    release_date: string,
    running_time: string,
    screenwriters: Array<string>,
    slug: string,
    summary: string,
    title: string,
    trailer: string,
    wiki: string
}